version: "2.1"

volumes:
    onesketchaday_media:
    onesketchaday_static:
    onesketchaday_config:
    onesketchaday_db:

networks:
    backend:

services:
    db:
        image: mariadb
        container_name: onesketchaday_db
        volumes:
            - onesketchaday_db:/var/lib/mysql
        networks:
            backend:
        env_file:
            - variables.env
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            start_period: 10s
            interval: 10s
            timeout: 5s
            retries: 3

    app:
        container_name: onesketchaday_app
        image: onesketchaday
        build: .
        volumes:
            - ./sockets:/sockets
            - onesketchaday_config:/config
            - onesketchaday_media:/onesketchaday/media
            - onesketchaday_static:/onesketchaday/static
            - ./django-token:/onesketchaday/django-token
            - ./discord-token:/onesketchaday/discord-token
        depends_on:
            db:
              condition: service_healthy
        networks:
            backend:
        env_file:
            - variables.env